### ISSUE TITLE
Need function to generate extent from a range of input types

### ISSUE THREAD

**Issue by ericrobskyhuntley** [ographiesresearch/urbanplanr#47]
Function `st_get_extent()` should be able to take the following input types and produce a polygonal extent:

+ [ ] `places` (`county`, `muni`, or `state`)
  + [ ] `county`
  + [ ] `muni`
  + [ ] `state`
+ [ ] `shape` (a path to a `geojson` or `shp`
+ [ ] `point` (with a given radius to buffer)

Configuration `yaml` should look like this:

```yaml
extent:
    places: 
        names: ["Cambridge, MA", "Somerville, MA"] # or "Middlesex [County], MA", or "MA"
        type: "muni" # or "county" or "state
    point:
        coords: [42.360, -71.094]
        dist: 0.25 # in miles
    shape: "data/extent.geojson"
```

Test with...

```r
st_get_extent(
  2249,
  places = list(
    names = c("Cambridge, MA", "Somerville, MA"),
    type = "muni"
  )
)

st_get_extent(
  2249,
  places = list(
    names = c("Middlesex, MA", "Suffolk, MA"),
    type = "county"
  )
)

st_get_extent(
  2249,
  places = list(
    names = c("MA", "RI"),
    type = "state"
  )
)

st_get_extent(
  2249,
  point = list(
    coords = c(42.360, -71.094),
    dist = 0.25,
    name = "MIT DUSP"
  )
)

st_get_extent(
  2249,
  path = "https://gist.githubusercontent.com/ericrobskyhuntley/f903841d3dc2f144b97d57931a5308c8/raw/732414d84722c19b4777f9fcb486a1c7d9d7b4a8/sample.geojson" 
)
```
